
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author briam
 */
<<<<<<< HEAD:proyectoUltimaVersion/src/GUI.java
public class GUI extends javax.swing.JFrame {

    Test test = new Test();
=======
public class GUI extends javax.swing.JFrame implements Runnable
{

    Test test;
    Thread hilo;
    String d;
    boolean modoDeCaptura;
    
>>>>>>> b0a77a1b2ac807f78b16e139d104a7e3c283c2b6:proyecto/src/GUI.java

    public void setTablaSniffer(JTable TablaSniffer) {
        this.TablaSniffer = TablaSniffer;
    }
<<<<<<< HEAD:proyectoUltimaVersion/src/GUI.java

    public GUI() {
        initComponents();
        inicio.enable(false);
        test.llenarComboBoxDispositivos(dispositivosCB);
        promiscuo.setSelected(true);

=======
    /*
    private GUI(JTable TablaSniffer, String d, boolean modoDeCaptura, Test test) {
        this.modoDeCaptura=modoDeCaptura;
        this.d=d;
        this.test=test;
        setTablaSniffer(TablaSniffer);
        
        
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });//
        
    }
    */
    /*
    @Override
    public void run(){
        
        test.llenarTabla(TablaSniffer, d, modoDeCaptura);
    }*/
    
    public GUI() {
        
        this.test = new Test();
        initComponents(); 
        inicio.enable(false);
        test.llenarComboBoxDispositivos(dispositivosCB);
        promiscuo.setSelected(true);
        this.setVisible(true);
        
>>>>>>> b0a77a1b2ac807f78b16e139d104a7e3c283c2b6:proyecto/src/GUI.java
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModoCapura = new javax.swing.ButtonGroup();
        inicio = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        botonIniciar = new javax.swing.JButton();
        dispositivosCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        promiscuo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        no_promiscuo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSniffer = new javax.swing.JTable();
        botonRegresar = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        botonDeneter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciones el dispositivo");

        ModoCapura.add(promiscuo);
        promiscuo.setText("Promiscuo");

        jLabel2.setText("Seleccionar modo de captura de datos");

        ModoCapura.add(no_promiscuo);
        no_promiscuo.setText("No promiscuo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_promiscuo)
                    .addComponent(jLabel2)
                    .addComponent(promiscuo)
                    .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispositivosCB, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dispositivosCB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(promiscuo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no_promiscuo)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        inicio.addTab("Inicio", jPanel2);

        TablaSniffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaSniffer);

        botonRegresar.setText("REGRESAR");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonContinuar.setText("CONTINUAR");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        botonDeneter.setText("DETENER");
        botonDeneter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeneterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonDeneter, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegresar)
                    .addComponent(botonContinuar)
                    .addComponent(botonDeneter))
                .addGap(24, 24, 24))
        );

        inicio.addTab("Sniffer", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        // TODO add your handling code here:
        inicio.setSelectedIndex(1);
        botonContinuar.setEnabled(false);
        modelarTablaDeSniffer();
        


    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        inicio.setSelectedIndex(0);
        test.terminarLlenadoDeTabla();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonDeneterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeneterActionPerformed
        // TODO add your handling code here:
        test.detenerLlenadoDeTabla();
        botonContinuar.setEnabled(true);
        botonDeneter.setEnabled(false);
    }//GEN-LAST:event_botonDeneterActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        // TODO add your handling code here:
        botonContinuar.setEnabled(false);
        botonDeneter.setEnabled(true);
        test.continuarLLenadoDeTabla();
        
    }//GEN-LAST:event_botonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    /*
    public static void main(String args[]) {
<<<<<<< HEAD:proyectoUltimaVersion/src/GUI.java
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
=======
        
>>>>>>> b0a77a1b2ac807f78b16e139d104a7e3c283c2b6:proyecto/src/GUI.java
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });

    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ModoCapura;
    private javax.swing.JTable TablaSniffer;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonDeneter;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> dispositivosCB;
    private javax.swing.JTabbedPane inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton no_promiscuo;
    private javax.swing.JRadioButton promiscuo;
    // End of variables declaration//GEN-END:variables

    private void modelarTablaDeSniffer() {
<<<<<<< HEAD:proyectoUltimaVersion/src/GUI.java

=======
        
        
        Thread hhi = new Hilo_mensajes("primero",this.TablaSniffer);
        
        hhi.start();
        ///*
>>>>>>> b0a77a1b2ac807f78b16e139d104a7e3c283c2b6:proyecto/src/GUI.java
        DefaultTableModel model = new DefaultTableModel();
        this.TablaSniffer.setModel(model);
        TablaSniffer.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Número", "Tiempo", "Fuente", "Destino", "Protocolo", "Tamaño", "Información"
                }
        ));
        String dispositivoSeleccionado = dispositivosCB.getSelectedItem().toString();//PARA BUSCAR EL DISPOSITIVO SELECIONADO
        Boolean modoDeCaptura = null;
        if (promiscuo.isSelected()) {
            modoDeCaptura = true;
        } else {
            modoDeCaptura = false;
        }
<<<<<<< HEAD:proyectoUltimaVersion/src/GUI.java

        test.llenarTabla(TablaSniffer, dispositivoSeleccionado, modoDeCaptura);

    }

=======
        
        test.llenarTabla(TablaSniffer, d, modoDeCaptura);
        //*/
        
    }

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
>>>>>>> b0a77a1b2ac807f78b16e139d104a7e3c283c2b6:proyecto/src/GUI.java
}
